# Generated by Django 5.2.6 on 2025-09-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keyboards', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
